ehcache.configXml=ehcache.xml
j2cache.L1.provider_class=ehcache
j2cache.L2.config_section=redis
j2cache.L2.provider_class=net.oschina.j2cache.cache.support.redis.SpringRedisProvider
j2cache.broadcast=net.oschina.j2cache.cache.support.redis.SpringRedisPubsubPolicy
j2cache.l2-cache-open=true
redis.hosts=localhost:6379
redis.mode=single
redis.namespace=j2cache
