---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luo13.
--- DateTime: 2026/4/15 08:25
---
--比较线程标示与锁中的标示是否一致
if(redis.call('get',KEYS[1]) == ARGV[1])  then
    --释放锁 del key
    return redis.call('del', KEYS[1])
end
return